name: Check and deploy

on:
  push:
    branches:
      - "**"

jobs:
  check-upstream-src-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/School-of-Digital-Competencies/js-ts-tasks
          git fetch upstream

      - name: Compare changes with upstream
        id: check_files
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $CURRENT_BRANCH"
          
          if ! git ls-remote --exit-code --heads upstream $CURRENT_BRANCH; then
            echo "Branch $CURRENT_BRANCH does not exist in upstream."
            exit 1
          fi
          
          CHANGED_FILES=$(git diff --name-only upstream/$CURRENT_BRANCH HEAD)
          
          echo "Changed files: $CHANGED_FILES"
          
          INVALID_CHANGES=$(echo "$CHANGED_FILES" | grep -v -E '^src/' || true)
          echo "Invalid changed files: $INVALID_CHANGES"
          
          if [ -n "$INVALID_CHANGES" ]; then
            echo "Detected invalid changes outside 'src/' folders."
            echo "Invalid changes: $INVALID_CHANGES"
            exit 0
          fi

  deploy-to-pages:
    needs: check-upstream-src-changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check and create gh-pages branch if needed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          if ! git show-ref --verify --quiet refs/heads/gh-pages; then
            echo "Branch gh-pages does not exist. Creating it."
            git checkout --orphan gh-pages
            git rm -rf .
            touch .nojekyll
            git add .nojekyll
            git commit -m "Initialize gh-pages branch"
            git push origin gh-pages
          else
            echo "Branch gh-pages already exists."
          fi

      - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages
          git rm -rf .
          cp -r ./dist/* ./

          git add .
          git commit -m "Deploy: $(date -u +"%Y-%m-%d %H:%M:%S")"
          git push --force origin gh-pages

#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./src
